### ISSUE TITLE
コミット漏れのファイルがあります

### ISSUE THREAD

**Issue by kanedahiroshi** [runceel/PrismEdu#1]
以下の5つのファイルのコミットが漏れています。
03.Module/ModuleApp/App.xaml
05.InteractionRequest/InteractionRequestSampleModule/ViewModels/InputViewModel.cs
05.InteractionRequest/InteractionRequestSampleModule/Views/InputView.xaml
05.InteractionRequest/InteractionRequestSampleModule/Views/InputView.xaml.cs
05.InteractionRequest/InteractionRequestSampleModule/Views/InteractionRequestView.xaml

解説参考にさせてもらいました。
ありがとうございます。

**Comment by runceel** [comment]
ご指摘ありがとうございます！

追加してみました。
どうでしょうか

**Comment by kanedahiroshi** [comment]
サンプルソフトを試せるようになりました。
対応ありがとうございます。
